# Generated by Django 5.0.1 on 2024-01-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=45)),
                ('prenume', models.CharField(max_length=45)),
                ('adresa', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=45)),
                ('tara_origine', models.CharField(max_length=60)),
                ('adresa', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ProdusAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire', models.CharField(max_length=60)),
                ('data_producere', models.DateTimeField()),
                ('data_expirare', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_comanda', models.DateTimeField()),
                ('producator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producator')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produsalimentar')),
            ],
        ),
        migrations.CreateModel(
            name='Achizitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_achizitie', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produsalimentar')),
            ],
        ),
    ]
