# Generated by Django 5.0.1 on 2024-01-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='nume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenume',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produsalimentar',
            name='data_expirare',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produsalimentar',
            name='data_producere',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='produsalimentar',
            name='denumire',
            field=models.CharField(max_length=100),
        ),
    ]
